### PR TITLE
Fix #1538: synchronise repeat between tabs and bg

### LINKED ISSUE #1538: `repeat` seems to be broken
### Description of the problem

- `repeat` command does not seem to work on Tridactyl version `1.14.10-212-g70fa456`

### Steps to reproduce

- Navigate to `https://github.com/tridactyl/tridactyl/issues/1537`
- Perform `urlincrement` or `urldecrement` operation e.g. using `C-a` or `C-x` key
- Perform `repeat` operation e.g. using `.` key

   - **_Nothing happens on `repeat`_**

### Software Versions

- Tridactyl version : `1.14.10-212-g70fa456`
- Firefox version   : `Developer Edition 67.0b18 (64-bit)`

### PR DESCRIPTION
**Pull request by bovine3dom**
This has exposed the fragility of the state lock, however -

```
:tabopen news.bbc.co.uk
10.
# close the 10 tabs once they've loaded a bit
:js alert("blah")
:<ArrowUp> # no new entries can be added to command history
```

I suspect we just need an, e.g. 1 second timeout on the locks at which point they give up and take the lock anyway.

### CODE REVIEW

File: src/lib/locks.ts [hunk 1]
```diff
@@ -19,13 +22,33 @@ export async function acquire(lockname: string) {
...
 
     delete DESIRED_LOCKS[lockname]
     OWNED_LOCKS.add(lockname)
 }
 
+/**
+ * Execute func after acquiring a named lock. If func takes longer than timeout, release the lock early.
+ * Returns the value of func.
+ */
+export async function withlock(lockname: string, func, timeout= 2000) {
```
Comment (bovine3dom) [inline src/lib/locks.ts]: Is that what you were suggesting @glacambre ?
